ashtonkbailey/wheel-of-fortune-m2

- index.html
- styles.css
Added html comments to identify the two main sections of our page and added css comments to identify each main section of the page styling
> Added html and css comments

- tests/BonusRound-test.js
- tests/Game-test.js
- tests/Player-test.js
- tests/Puzzle-test.js
- tests/Round-test.js
- tests/Wheel-test.js
only includes the require statements
> Create test files for each file

- domUpdates.js
- index.html
- script.js
Added functionality to the "start button" that changes the text of the player number labels to the input values of the player names
> Add function to update player names on home page

- domUpdates.js
- index.html
- script.js
- styles.css
Added functionality that adds animation to the game board once the "start button" is clicked.
> Add more start game functionality

- Player.js
- Puzzle.js
- Round.js
- Wheel.js
Also-Write a function for choosing a value from the wheel at random on spin
> Write a function for generating a new wheel for each round.

- Puzzle.js
- Wheel.js
- domUpdates.js
- test/Puzzle-test.js
and function to add correct letters to guessedLetter property
> Write function to split the puzzle's answer

- Player.js
- test/Player-test.js
Added test for our Player class. Last test is still failing- getting the error "data is not defined."
@thatPamIAm
@brittanystoroz
> Player test

- Player.js
- domUpdates.js
- index.html
- script.js
- styles.css
- test/Player-test.js
Added function to change the opacity of the letter after 'click' so that player knows which letter has already been guessed
> Add disable letter function

- Player.js
- domUpdates.js
- test/Player-test.js
Added a method to update the score after a player guesses a consonant and the guess is correct. Also created a test for that method.
> Add method on player to update score

- Player.js
- Puzzle.js
- test/Player-test.js
- test/Puzzle-test.js
Added two methods on Puzzle: checkGuessedVowel() and checkSolvePuzzle() and created tests for them. Neither of the tests are passing. 
Also added a method to Player: buyVowel() and created a test for it. Test is passing.
> Add buy vowel and solve puzzle methods and tests

- Game.js
- Puzzle.js
- Round.js
- test/Game-test.js
- test/Player-test.js
- test/Puzzle-test.js
added logic to determine whether to move to the next player. This broke the test for it. The error says 'game' in the conditional is undefined. No idea why.
@thatPamIAm
@brittanystoroz
> Changed checkGuessedLetter function in Puzzle class

- Game.js
- Round.js
- domUpdates.js
- index.html
- script.js
- styles.css
Started the switch player method on the round class. No test written yet.
> Switch player

- Player.js
- Puzzle.js
- Round.js
- domUpdates.js
- index.html
- script.js
Added a 'display-score' method but it is not working yet.
> Display score

- Puzzle.js
- Round.js
- domUpdates.js
- index.html
- script.js
- styles.css
- test/Round-test.js
Created method that shows all of the white tiles on the puzzle board based on the  length of the correct answer and created another method that shows the correct letter that was guessed on the puzzle board
> Board letters

- Game.js
- Player.js
- Puzzle.js
- Round.js
- Wheel.js
- domUpdates.js
- index.html
- script.js
- styles.css
The score now updates when guessing the correct vowel. When it's wrong it will switch players. The solve puzzle button pulls up an input and button to guess the answer. If it is wrong the player prompt changes and switchPlayer is called. The specs didn't say anything about losing points so I opted not to change the score. Next we need to write the functionality for a correct guess.
> Update score w vowel

- Puzzle.js
- domUpdates.js
Just need to invoke the function wherever a new turn is being called!
> Add method to change player name animation based on who's turn it is

- Player.js
- Puzzle.js
- Round.js
- domUpdates.js
- index.html
- script.js
The grand total is updated, the scores are reset, the game's currentround is updated, a new round is called
> Fix end of round functionality

- Puzzle.js
- Round.js
- domUpdates.js
there may be some issues with the player flashing when it switches after the bankruptcy. it's just one function on round that handles all of it so maybe we need to call the function that changes the flash inside of it...?
> Reset score and switch player

- Player.js
- Puzzle.js
- Round.js
- domUpdates.js
- index.html
- script.js
- styles.css
Still need to add functionality to check if the vowel that was bought is correct and if so, display that letter on the board, if not, switch player
> Add method to subract from total when buying a vowel

- Game.js
- Round.js
- domUpdates.js
Buy Vowel button will subtract $100 from current player's score (one time) and will check if the vowel selected is correct. If correct, vowel will display on the puzzle board
> Finish all functionality for the buy-vowel button

- Game.js
- Puzzle.js
- Round.js
- domUpdates.js
- styles.css
puzzle board now removes old answer and throws new puzzle blanks up.  the used consonants and vowels go back to original state
> Reset puzzle board and letters

- Puzzle.js
- domUpdates.js
- styles.css
hides vowel pop up after clicking vowel
> Final final vowel

- domUpdates.js
- index.html
- styles.css
letters start with a class that blocks click events until player clicks the spin button. after the letter is guessed the class is added back.
> Disable letters unless spin is clicked

- domUpdates.js
- index.html
- script.js
- styles.css
> Add blur class on page start

- Game.js
- Puzzle.js
- domUpdates.js
- index.html
- script.js
- styles.css
positioned correctly but needs some styling
> Build modal for winning round

- BonusRound.js
- Game.js
- Puzzle.js
- Round.js
- Wheel.js
- index.html
- script.js
gets two word puzzle and displays it. still needs to show a couple of consonants on puzzle to start
> Add method to start bonus round with new puzzle and new wheel

- BonusRound.js
- BonusWheel.js
- Player.js
- Puzzle.js
- Round.js
- domUpdates.js
- index.html
- styles.css
- test/BonuesWheel-test.js
- test/Game-test.js
- test/Player-test.js
- test/Puzzle-test.js
- test/Round-test.js
- test/domUpdates-test.js
Linted every file except bonusRound!
> Lint every file

- Wheel.js
- test/BonusRound-test.js
- test/Game-test.js
- test/Player-test.js
- test/Puzzle-test.js
- test/Round-test.js
- test/Wheel-test.js
Made more tests for every class. Most are passing. Still some failing. Keep getting "game is not defined" error.
> Add more tests
